### ISSUE TITLE
LOINC code 47213-4 should be excluded?

### ISSUE THREAD

**Issue by indera** [CDMFORUM/CDM-ERRATA#17]
One of our team members noticed that the LOINC code 47213-4 is listed on page 52
of the CDM pdf document but is missing from the Implementation guide v1.0 
available at https://pcornet.imeetcentral.com/drnoc-workgroups/doc/48336560/

Is this correct?

LOINC reference:
http://r.details.loinc.org/LOINC/47213-4.html?sections=Comprehensive

**Comment by smerek** [comment]
Thank you for this great question.  The CDM v3.0 specification includes the original laboratory code reference table, “Reference Table 1: Laboratory Results and LOINC Codes.”

An updated laboratory reference table was subsequently developed, and this is the one included in the Implementation Guidance posted on iMeetCentral.

The specific LOINC code you reference was intentionally left out of the updated laboratory reference table (because it refers to the size of LDL cholesterol particles in the blood, rather than the LDL level in the blood).

If you believe that LOINC code 47213-4 should be mapped to the “LDL” value in the LAB_NAME field, please let us know so that we can re-consider including it in the laboratory reference table.

**Comment by indera** [comment]
Michelle, am fine with the LOINC code 47213-4 being left out.
According to guidance we we can still include the results with 47213-4 but leave the LAB_NAME empty if we need it. You can close this issue if you consider this is solved.
